### ISSUE TITLE
PiSugar 1 not charging

### ISSUE THREAD

**Issue by andrewodri** [PiSugar/PiSugar#4]
I am encountering an issue with both a 900mAh and 1200mAh PiSugar module where the devices will not charge.

**Expected behavior**

1. Connect microUSB cable
2. All 4 blue LEDs blink for about 0.5-1 second
3. At low charge, a series of LEDs should illuminate, with a subsequent one blinking
4. At full charge, all 4 blue LEDs should remain illuminated

**Actual behavior**

1. Connect microUSB cable
2. First blue LED remains illuminated

When attached to a Pi Zero, these units do not power up.

I did have one unit that exhibited this behavior, then after the battery shifted, the LEDs illuminated very dimly, then it started to behave as expected with LEDs as full brightness. I suspected this could be an indicator that the battery could have dropped below a safe voltage, perhaps there was a shirt circuit, or something else... Any insight you can give would be appreciated!

**Comment by JdaieLin** [comment]
Hi andrew, it is an indicator that the battery has a very low voltage. 

It will behave like this:

1. Connect micro USB cable
2. First blue LED remains illuminated (bright)
3. A few minutes later, first blue LED start to blink (dim to bright)
4. Shift to normal charging behavior

It happens when it was idle for a few weeks. We usually charge at least one time a month.
If it was idle for too long, like a few month, it might not be able to shift to normal charging behavior since the lithium will naturelly become inactive when it stay in low votage.
