### ISSUE TITLE
PiSugar3 Plus solar power

### ISSUE THREAD

**Issue by xevilstar** [PiSugar/PiSugar#90]
how can I connect a solar panel to my PiSugar3 Plus ?

**Comment by CausalityRetro** [comment]
I got one of [these](https://www.amazon.com.au/dp/B0B5G2BD5P?psc=1&ref=ppx_yo2ov_dt_b_product_details) and it seems to work well enough. Has the required 5V and I believe it's charging the battery faster than my RPi timelapse camera is draining it. Hard to tell because I can't seem the read the capacity...
